version: '3'

services:
  # MySQL
  db:
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 33066:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'mysql'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
    volumes:
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'

  opana_web:
      build: .
      command: python /usr/src/opana_rest/manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/usr/src/opana_rest
      ports:
        - 8000:8000
      depends_on:
        - db